export const REQUEST_LIBRARY_LIST = 'REQUEST_LIBRARY_LIST';
export const RECEIVE_LIBRARY_LIST = 'RECEIVE_LIBRARY_LIST';
export const REQUEST_CREATE_LIBRARY = 'REQUEST_CREATE_LIBRARY';
export const RECEIVE_CREATE_LIBRARY = 'RECEIVE_CREATE_LIBRARY';