export const LIBRARY_LIST_SELECT_LIBRARY = 'LIBRARY_LIST_SELECT_LIBRARY';
export const LIBRARY_LIST_SELECT_LIBRARY_MENU = 'LIBRARY_LIST_SELECT_LIBRARY_MENU';
export const LIBRARY_LIST_SET_FILTER_TEXT = 'LIBRARY_LIST_SET_FILTER_TEXT';

export const LIBRARY_CREATE_OPEN = 'LIBRARY_CREATE_OPEN';
export const LIBRARY_CREATE_SAVE = 'LIBRARY_CREATE_SAVE';
export const LIBRARY_CREATE_CANCEL = 'LIBRARY_CREATE_CANCEL';

export const LIBRARY_EDIT_DETAILS_OPEN = 'LIBRARY_EDIT_DETAILS_OPEN';
export const LIBRARY_EDIT_TAGS_OPEN = 'LIBRARY_EDIT_TAGS_OPEN';
export const LIBRARY_EDIT_SYNCS_OPEN = 'LIBRARY_EDIT_SYNCS_OPEN';
export const LIBRARY_EDIT_SEARCHES_OPEN = 'LIBRARY_EDIT_SEARCHES_OPEN';

export const EDIT_LIBRARY_OPEN = 'EDIT_LIBRARY_OPEN';

export const DELETE_LIBRARY_OPEN = 'DELETE_LIBRARY_OPEN';


// api

export const CREATE_LIBRARY_REQUEST = 'CREATE_LIBRARY_REQUEST';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_FAILURE = 'CREATE_LIBRARY_FAILURE';

export const UPDATE_LIBRARY_REQUEST = 'UPDATE_LIBRARY_REQUEST';
export const UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS';
export const UPDATE_LIBRARY_FAILURE = 'UPDATE_LIBRARY_FAILURE';

export const FETCH_LIBRARIES_REQUEST = 'FETCH_LIBRARIES_REQUEST';
export const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_FAILURE = 'FETCH_LIBRARIES_FAILURE';


export const SET_CREATE_LIBRARY_DIALOG_OPEN_STATUS = 'SET_CREATE_LIBRARY_DIALOG_OPEN_STATUS';
