export const FETCH_LIBRARIES_REQUEST = 'FETCH_LIBRARIES_REQUEST';
export const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_FAILURE = 'FETCH_LIBRARIES_FAILURE';

export const CREATE_LIBRARY_DIALOG_OPEN = 'CREATE_LIBRARY_DIALOG_OPEN';
export const CREATE_LIBRARY_DIALOG_SAVE = 'CREATE_LIBRARY_DIALOG_SAVE';
export const CREATE_LIBRARY_DIALOG_CANCEL = 'CREATE_LIBRARY_DIALOG_CANCEL';


export const EDIT_LIBRARY_OPEN = 'EDIT_LIBRARY_OPEN';

export const DELETE_LIBRARY_OPEN = 'DELETE_LIBRARY_OPEN';


export const CREATE_LIBRARY_REQUEST = 'CREATE_LIBRARY_REQUEST';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_FAILURE = 'CREATE_LIBRARY_FAILURE';

export const UPDATE_LIBRARY_REQUEST = 'UPDATE_LIBRARY_REQUEST';
export const UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS';
export const UPDATE_LIBRARY_FAILURE = 'UPDATE_LIBRARY_FAILURE';

export const NAVIGATOR_SELECT_LIBRARY = 'NAVIGATOR_SELECT_LIBRARY';
export const NAVIGATOR_SELECT_LIBRARY_MENU = 'NAVIGATOR_SELECT_LIBRARY_MENU';